# Generated by Django 4.0.4 on 2022-06-03 05:42

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.CharField(default=chat.models.pkgen, max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='communication.account')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.CharField(default=chat.models.pkgen, max_length=20, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('messages', models.ManyToManyField(blank=True, related_name='chats', to='chat.message')),
                ('participants', models.ManyToManyField(related_name='chats', to='communication.account')),
            ],
        ),
    ]
