# Generated by Django 4.0.4 on 2022-05-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_date_account_friends_account_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
