# Generated by Django 4.0.4 on 2022-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
