# Generated by Django 4.0.5 on 2022-06-10 07:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('requester', 'receiver'), name='unique_friendship_reverse'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.CheckConstraint(check=models.Q(('requester', django.db.models.expressions.F('receiver')), _negated=True), name='prevent_self_follow'),
        ),
    ]
