# Generated by Django 4.0.5 on 2022-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_friendrequest_unique_friendship_reverse_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friendship_reverse',
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('requester', 'receiver'), name='unique_friend_request'),
        ),
    ]
