# Generated by Django 4.0.5 on 2022-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_remove_friendrequest_unique_friendship_reverse_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friend_request',
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('requester', 'receiver', 'accepted'), name='unique_friend_request'),
        ),
    ]
